name: pyinstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - uses: jcwillox/install-tool-action@v1
      with:
        repo: "upx/upx"
        download_url: "/releases/download/v4.2.4/upx-4.2.4-win64.zip"
        bin_path: "upx-4.2.4-win64"

    - run: pip install -r requirements.txt
    - run: pip install pyinstaller garth
    - run: pyinstaller standalone.spec

    - uses: vimtor/action-zip@v1.2
      with:
        files: dist
        dest: zoffline-nightly.zip

    - uses: WebFreak001/deploy-nightly@v3.1.0
      with:
        upload_url: https://uploads.github.com/repos/oldnapalm/zwift-offline/releases/188899554/assets{?name,label}
        release_id: 188899554
        asset_path: zoffline-nightly.zip
        asset_name: zoffline-nightly.zip
        asset_content_type: application/zip
